FROM ruby:2.7.1

# Add yarn
RUN curl https://deb.nodesource.com/setup_12.x | bash
RUN curl https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
RUN echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list
RUN apt-get update -qq && apt-get install -y nodejs postgresql-client yarn

# Create directory
# ENV RAILS_ROOT /bbb-demo2
# RUN mkdir -p $RAILS_ROOT 

RUN mkdir /bbb-demo2
WORKDIR /bbb-demo2
# Set working directory
# WORKDIR $RAILS_ROOT

# Setting env up
ENV RAILS_ENV='production'
ENV RACK_ENV='production'

COPY Gemfile Gemfile
COPY Gemfile.lock Gemfile.lock
RUN bundle install
RUN yarn install --check-files
COPY . /bbb-demo2
# RUN rake db:create db:migrate db:seed

# Add a script to be executed every time the container starts.
COPY entrypoint.sh /usr/bin/
RUN chmod +x /usr/bin/entrypoint.sh
ENTRYPOINT ["entrypoint.sh"]
EXPOSE 3000

# Start the main process.
CMD ["rails", "server", "-b", "0.0.0.0"]
# CMD ["bundle", "exec", "puma", "-C", "/config/puma.rb"]