version: '3'
services:
    app:
        build:
            context: .
            dockerfile: ./docker/app/DockerFile
        depends_on: 
            - db
    db:
        image: postgres
        volumes:
        - ./tmp/db:/var/lib/postgresql/data
        ports:
        - '5432' 
    web:
        build: 
            context: .
            dockerfile: ./docker/web/DockerFile
        depends_on:
            - app
        ports:
            - 80:80
        restart: always